apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: real-service-user-api
  description: Stores artist details
spec:
  type: database
  owner: infrastructure
  system: real-service-user-api
